import "./globals.css";
import { Figtree, Lexend } from "next/font/google";

const figtree = Figtree({ subsets: ["latin"], weight:'variable' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
